### ISSUE TITLE
loaddata edit,delete

### ISSUE THREAD

**Issue by leehosu** [leehosu/ToDoList_Hosu#43]
load한 date들 edit, delete

**Comment by y0c** [comment]
localStorage 에 저장된 데이터는 `HTML을 문자열`로 저장해놓은 거라서 이 방식으로 하려면 `event`를 다시 걸어줘야되.
`event` 가 처음에는 걸려있다가 문자열로 저장할땐 같이 저장이 안되고 있는거야. 
`event delegate` 로 해결할 수 있고 localStorage에 HTML이 아니라 `todo 에 대한 데이터`를 저장하면 좀 더 나은처리를 할수있어. 근데 `event delegate` 를 공부하면서 그걸로 먼저 처리해봐도 나쁘지 않을듯
